// import myAxios from '@/plugins/myAxios'

import { useTerminalConfigStore } from '@/stores/terminalConfigStore'

// export const getBackground = async () => {
//   return await myAxios.post('/background/get/random')
// }

let pictures = [
  'https://w.wallhaven.cc/full/gp/wallhaven-gp1yx7.jpg',
  'https://w.wallhaven.cc/full/zy/wallhaven-zy2x7v.png',
  'https://w.wallhaven.cc/full/m3/wallhaven-m3rdj1.jpg',
  'https://w.wallhaven.cc/full/l8/wallhaven-l8rqjp.png',
  'https://w.wallhaven.cc/full/jx/wallhaven-jxr8eq.jpg',
  'https://w.wallhaven.cc/full/gp/wallhaven-gpv8wl.png',
  'https://w.wallhaven.cc/full/m3/wallhaven-m3ox3k.jpg',
  'https://w.wallhaven.cc/full/85/wallhaven-858lz1.png',
  'https://w.wallhaven.cc/full/5g/wallhaven-5gpv25.jpg',
  'https://w.wallhaven.cc/full/1p/wallhaven-1pojx3.jpg',
  'https://w.wallhaven.cc/full/gp/wallhaven-gp1977.jpg',
  'https://w.wallhaven.cc/full/zy/wallhaven-zyv2kg.png',
  'https://w.wallhaven.cc/full/85/wallhaven-858z32.jpg',
  'https://w.wallhaven.cc/full/p9/wallhaven-p95lv3.jpg',
  'https://w.wallhaven.cc/full/yx/wallhaven-yxw5wk.jpg',
  'https://w.wallhaven.cc/full/yx/wallhaven-yxw5wl.jpg',
  'https://w.wallhaven.cc/full/9d/wallhaven-9dezkd.jpg',
  'https://w.wallhaven.cc/full/jx/wallhaven-jxl31y.png',
  'https://w.wallhaven.cc/full/7p/wallhaven-7pje5o.png',
  'https://w.wallhaven.cc/full/rr/wallhaven-rrowwm.png',
  'https://w.wallhaven.cc/full/ex/wallhaven-exwgw8.png',
  'https://w.wallhaven.cc/full/l8/wallhaven-l8z9jr.jpg',
  'https://w.wallhaven.cc/full/d6/wallhaven-d63xgl.jpg',
  'https://w.wallhaven.cc/full/we/wallhaven-weeqzx.jpg',
  'https://w.wallhaven.cc/full/jx/wallhaven-jx3gxy.jpg',
  'https://w.wallhaven.cc/full/o5/wallhaven-o5g6r7.png',
  'https://w.wallhaven.cc/full/x6/wallhaven-x6dj5z.png',
  'https://w.wallhaven.cc/full/l8/wallhaven-l8896l.png',
  'https://w.wallhaven.cc/full/l8/wallhaven-l83o6q.png',
  'https://w.wallhaven.cc/full/zy/wallhaven-zyyx1o.jpg',
  'https://w.wallhaven.cc/full/zy/wallhaven-zyyx1o.jpg',
  'https://w.wallhaven.cc/full/zy/wallhaven-zyyx1o.jpg',
  'https://w.wallhaven.cc/full/zy/wallhaven-zyyx1o.jpg',
  'https://w.wallhaven.cc/full/zy/wallhaven-zyyx1o.jpg',
  'https://w.wallhaven.cc/full/zy/wallhaven-zyyx1o.jpg',
  'https://w.wallhaven.cc/full/kx/wallhaven-kxr89q.png',
  'https://w.wallhaven.cc/full/kx/wallhaven-kxr89q.png',
  'https://w.wallhaven.cc/full/zy/wallhaven-zy2pwo.jpg',
  'https://w.wallhaven.cc/full/ex/wallhaven-exr858.jpg',
  'https://w.wallhaven.cc/full/1p/wallhaven-1plq5g.jpg',
  'https://w.wallhaven.cc/full/1p/wallhaven-1plq5g.jpg',
  'https://w.wallhaven.cc/full/qz/wallhaven-qzp8dr.png',
  'https://w.wallhaven.cc/full/qz/wallhaven-qzp8dr.png',
  'https://w.wallhaven.cc/full/kx/wallhaven-kxj3l1.jpg',
  'https://w.wallhaven.cc/full/we/wallhaven-wexkp6.png',
  'https://w.wallhaven.cc/full/ex/wallhaven-exw1jk.jpg',
  'https://w.wallhaven.cc/full/28/wallhaven-281d5y.png',
  'https://w.wallhaven.cc/full/28/wallhaven-281d5y.png',
  'https://w.wallhaven.cc/full/28/wallhaven-281d5y.png',
  'https://w.wallhaven.cc/full/28/wallhaven-281d5y.png',
  'https://w.wallhaven.cc/full/2e/wallhaven-2eq1gy.jpg',
  'https://w.wallhaven.cc/full/72/wallhaven-72pqze.jpg',
  'https://w.wallhaven.cc/full/72/wallhaven-72pqze.jpg',
  'https://w.wallhaven.cc/full/5w/wallhaven-5we787.jpg',
  'https://w.wallhaven.cc/full/z8/wallhaven-z8e8qy.jpg',
  'https://w.wallhaven.cc/full/z8/wallhaven-z8e8qy.jpg',
  'https://w.wallhaven.cc/full/z8/wallhaven-z8e8qy.jpg',
  'https://w.wallhaven.cc/full/vg/wallhaven-vg7lv3.jpg',
  'https://w.wallhaven.cc/full/vg/wallhaven-vg7lv3.jpg',
  'https://w.wallhaven.cc/full/k7/wallhaven-k7g117.jpg',
  'https://w.wallhaven.cc/full/y8/wallhaven-y8vlyk.jpg',
  'https://w.wallhaven.cc/full/ox/wallhaven-oxkjgm.jpg',
  'https://w.wallhaven.cc/full/7p/wallhaven-7pg1m9.jpg',
  'https://w.wallhaven.cc/full/pk/wallhaven-pkgkkp.png',
  'https://w.wallhaven.cc/full/rd/wallhaven-rdwjj7.jpg',
  'https://w.wallhaven.cc/full/v9/wallhaven-v96m6p.jpg',
  'https://w.wallhaven.cc/full/v9/wallhaven-v96m6p.jpg',
  'https://w.wallhaven.cc/full/v9/wallhaven-v96m6p.jpg',
  'https://w.wallhaven.cc/full/28/wallhaven-28mkg9.jpg',
  'https://w.wallhaven.cc/full/8o/wallhaven-8old52.jpg',
  'https://w.wallhaven.cc/full/j3/wallhaven-j3dg1m.jpg',
  'https://w.wallhaven.cc/full/j3/wallhaven-j3dg1m.jpg',
  'https://w.wallhaven.cc/full/zm/wallhaven-zmkwmv.jpg',
  'https://w.wallhaven.cc/full/zm/wallhaven-zmkwmv.jpg',
  'https://w.wallhaven.cc/full/6k/wallhaven-6kpko7.jpg',
  'https://w.wallhaven.cc/full/e7/wallhaven-e7g71w.jpg',
  'https://w.wallhaven.cc/full/zm/wallhaven-zmmkkv.png',
  'https://w.wallhaven.cc/full/ey/wallhaven-ey91w8.jpg',
  'https://w.wallhaven.cc/full/ey/wallhaven-ey91w8.jpg',
  'https://w.wallhaven.cc/full/ey/wallhaven-ey91w8.jpg',
  'https://w.wallhaven.cc/full/1j/wallhaven-1j6qj3.png',
  'https://w.wallhaven.cc/full/1j/wallhaven-1j6qj3.png',
  'https://w.wallhaven.cc/full/1j/wallhaven-1j6qj3.png',
  'https://w.wallhaven.cc/full/1j/wallhaven-1j6qj3.png',
  'https://w.wallhaven.cc/full/rr/wallhaven-rr3y61.jpg',
  'https://w.wallhaven.cc/full/rr/wallhaven-rr3y61.jpg',
  'https://w.wallhaven.cc/full/rr/wallhaven-rr3y61.jpg',
  'https://w.wallhaven.cc/full/57/wallhaven-572k81.png',
  'https://w.wallhaven.cc/full/57/wallhaven-572k81.png',
  'https://w.wallhaven.cc/full/r2/wallhaven-r25jdm.jpg',
  'https://w.wallhaven.cc/full/r2/wallhaven-r25jdm.jpg',
  'https://w.wallhaven.cc/full/kx/wallhaven-kxwp96.jpg',
  'https://w.wallhaven.cc/full/8o/wallhaven-8o2v82.jpg',
  'https://w.wallhaven.cc/full/8o/wallhaven-8o2v82.jpg',
  'https://w.wallhaven.cc/full/8o/wallhaven-8o2v82.jpg',
  'https://w.wallhaven.cc/full/3l/wallhaven-3lov33.jpg',
  'https://w.wallhaven.cc/full/3l/wallhaven-3lov33.jpg',
  'https://w.wallhaven.cc/full/ox/wallhaven-ox678m.jpg',
  'https://w.wallhaven.cc/full/ox/wallhaven-ox678m.jpg',
  'https://w.wallhaven.cc/full/8o/wallhaven-8o3m71.jpg',
  'https://w.wallhaven.cc/full/5d/wallhaven-5d1m61.png',
  'https://w.wallhaven.cc/full/yj/wallhaven-yj1z57.png',
  'https://w.wallhaven.cc/full/3z/wallhaven-3zgk8d.jpg',
  'https://w.wallhaven.cc/full/q2/wallhaven-q2wrjl.jpg',
  'https://w.wallhaven.cc/full/kw/wallhaven-kwp5km.png'
]

export const getBackground = async () => {
  let res
  let pre
  res = pictures[Math.floor(Math.random() * pictures.length)]
  while (pre === res) res = pictures[Math.floor(Math.random() * pictures.length)]
  pre = res
  return res
}
